# Generated by Django 6.0.3 on 2026-04-09 12:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=144, unique=True)),
                ('description', models.TextField(blank=True)),
                ('user_id', models.UUIDField(editable=False)),
                ('group_id', models.IntegerField(blank=True, editable=False, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('unblock_date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=144, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageFollower',
            fields=[
                ('pk', models.CompositePrimaryKey('user_id', 'page_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='blog.page')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.page')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='blog.post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('pk', models.CompositePrimaryKey('user_id', 'post_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.post')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='pages', to='blog.tag'),
        ),
    ]
